### ISSUE TITLE
ENH,BUG,SEC: Jupyter support, HTML escaping

### ISSUE THREAD

**Issue by westurner** [astanin/python-tabulate#25]
I created a wrapper class to display HTML in JupyterLab; and then looked at the source and realized there's no cgi.escape / html.escape / bleach.clean / bleach.linkify; which (I assume) is an XSS vulnerability

```python
class TabulateHTML:
    def __init__(self, *args, **kwargs):
        kwargs['tablefmt'] = 'html'
        self.html = tabulate(*args, **kwargs)
    def _repr_html_(self):
        return self.html
TabulateHTML(output)
```

There's likely a better way to wrap TableFormat to return either an object with a ._repr_html_() method or an IPython.display.HTML when tablefmt='jupyterhtml' | 'jupyter' | 'ipython'?

https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display

https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.HTML

(edit)
Pull Requests:

- [ ] #26 BUG,SEC: html.escape to prevent XSS
- [ ] #27 ENH: return a wrapped str w/ a _repr_html_ so that Jupyter displays the html

**Comment by westurner** [comment]
This works as well:

```python
from tabulate import tabulate
def tabulate_jupyter(*args, **kwargs):
    import IPython.display
    kwargs['tablefmt'] = 'html'
    return IPython.display.HTML(tabulate(*args, **kwargs))

tabulate_jupyter(output)
```

**Comment by westurner** [comment]
html.escape is in Python >= 3.2
https://docs.python.org/3/library/html.html

**Comment by westurner** [comment]
Pull Requests:
- [ ] #26 BUG,SEC: html.escape to prevent XSS
- [ ] #27 ENH: return a wrapped str w/ a _repr_html_ so that Jupyter displays the html

**Comment by astanin** [comment]
Great. Thank you for the pull requests. Could you please also add a test case in test/test_regression.py?

**Comment by westurner** [comment]
I added tests in #27 (passing) and #26 (passing; see comments)

**Comment by westurner** [comment]
Thanks!

**Comment by westurner** [comment]
Any chance you could push a new release to PyPI with these security fixes?

**Comment by mchamlee-eig** [comment]
This change breaks the ability to build anchor tags (links) in html tables, they are all escaped. Possible to provide a way to turn this off, but leave the default to escape for security purposes?

**Comment by westurner** [comment]
Looks like #42 "adding in unsafe html format" adds support for `tablefmt="unsafehtml"`. How could that be a non-global setting for use with Jupyter `_repr_html_()`?

**Comment by mchamlee-eig** [comment]
Well, I tried `tablefmt="unsafehtml"` earlier today when I found the reference in the code, but either the functionality doesn't work the way I'm expecting it to, or something is broken.

Here is what I used to get prior to moving to 0.8.7, and what is desired:
![2020-04-21_16-47-41](https://user-images.githubusercontent.com/58988007/79926195-1de31600-83f1-11ea-8837-4ffa25d608be.png)

This is what I get as of 0.8.7 without any code changes:
![2020-04-21_16-48-37](https://user-images.githubusercontent.com/58988007/79926201-22a7ca00-83f1-11ea-8eb0-ebbdc6b70165.png)

And this is the result if I use `unsafehtml` instead of `html`:
![2020-04-21_16-47-41](https://user-images.githubusercontent.com/58988007/79926204-263b5100-83f1-11ea-927d-2bf5161d3853.png)

I haven't had time to dig deeper into the code to fully understand if this is desired functionality or a bug in the new process.

**Comment by westurner** [comment]
Does this addition to `test_output.py` test for that? https://github.com/astanin/python-tabulate/pull/42/files#diff-cb3d336647766ac81337e77a509b33e0

**Comment by mchamlee-eig** [comment]
Yes, it should.
